validation:
  ignore:
    - message: 'file /ext/vendor/bin/phpstan.phar is not allowed in the zip file'
    - message: 'file /ext/vendor/phpstan/phpstan/phpstan.phar is not allowed in the zip file'
    - message: 'file /ext/vendor/shopware/core/Framework/Test/Plugin/_fixture/archives/App.zip is not allowed in the zip file'
    - message: 'file /ext/vendor/shopware/core/Framework/Test/Plugin/_fixture/archives/NoPlugin.zip is not allowed in the zip file'
    - message: ' file /ext/vendor/shopware/core/Framework/Test/Plugin/_fixture/archives/NoZip.zip is not allowed in the zip file'
    - message: ' file /ext/vendor/shopware/core/Framework/Test/Plugin/_fixture/archives/SwagFashionTheme.zip is not allowed in the zip file'
    - message: 'file /ext/vendor/shopware/storefront/Resources/app/storefront/.eslintrc.js is not allowed in the zip file'
    - message: 'file /ext/vendor/shopware/storefront/Resources/app/storefront/stylelint.config.js is not allowed in the zip file'
    - message: 'file /ext/vendor/shopware/storefront/Resources/app/storefront/vendor/tiny-slider/src/.DS_Store is not allowed in the zip file'
    - message: 'the german description with length of 34 should have a length from 150 up to 185 characters.'
    - message: 'the english description with length of 34 should have a length from 150 up to 185 characters.'
